conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name = 'contact'),
    path('signup/', views.signup, name = 'signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'), 
]

item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('', views.browse, name='browse'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('cover_image/', views.cover_image, name='cover_image'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Cover_Image(models.Model):
    image = models.ImageField(upload_to='cover_images', blank=True, null=True)

    class Meta:
        verbose_name = 'Cover Image'
        verbose_name_plural = 'Cover Images'
    
    def __str__(self):
        return f"Cover Image {self.id}"

class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
    
    def __str__(self):
        return self.name
    
class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    descroption = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    

item/forms.py
from django import forms
from .models import Item                                                                                                                            

INPUT_CLASSES = "w-1/2 py-4 px-6 rounded-xl border bg-white-500 text-black"
class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'descroption', 'price', 'image')

        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES,

            }),
            'descroption': forms.Textarea(attrs={
                'class': INPUT_CLASSES,

            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES,

            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES,
            }),

    }
         


class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'descroption', 'price', 'image', 'is_sold')

        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES,

            }),
            'descroption': forms.Textarea(attrs={
                'class': INPUT_CLASSES,

            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES,

            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES,
            }),

    }
         

item/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from .models import Category, Item, Cover_Image
from .forms import NewItemForm, EditItemForm
from django.contrib.auth.decorators import login_required
import json
from django.http import HttpResponse
from django.http import JsonResponse

def cover_image(request):
    cover_images = Cover_Image.objects.all()
    if not cover_images:
        return render(request, 'item/cover_image.html', {'cover_image': None})
    else:
        cover_image = cover_images[0]
        return render(request, 'item/cover_image.html', {
            'cover_image': cover_image
            })
  
def browse(request):
    query = request.GET.get('query', '')
    category_id = int(request.GET.get('category', 0))
    categories = Category.objects.all()
    items = Item.objects.filter(is_sold=False)

    if category_id:
        items = items.filter(category_id=category_id)

    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))  # Fixed typo

    return render(request, 'item/browse.html', {
        'items': items,
        'query': query,
        'categories': categories,
        'category_id': category_id
    })  
# def browse(request):
#     query = request.GET.get('query', '')
#     category_id = request.GET.get('category', 0)
#     categories = Category.objects.all()
#     browse=Item.objects.filter(is_sold=False)

#     if category_id:
#         browse = browse.filter(category_id=category_id)
#         print("if_1 :",browse)

#     if query:
#         browse = browse.filter(Q(name__icontains=query) | Q(descroption__icontains=query))
#         print("if_2",browse)
#     items_data = [{
#         'id': item.id,
#         'name': item.name,
#         'description': item.descroption,
#         'price': item.price,
#         'image': item.image.url if item.image else None,
#         'category': item.category.name,
#         'is_sold': item.is_sold,
#         'created_by': item.created_by.username,
#         'created_at': item.created_at.isoformat()
#     } for item in browse]

#     # Serialize categories
#     categories_data = [{
#         'id': cat.id,
#         'name': cat.name
#     } for cat in categories]

#     return render(request, 'item/browse.html', {
#         'items': items,
#         'query': query,
#         'categories': categories,
#         'category_id': category_id
#     })
# json.dumps({'items': browse,
#         'query': query,
#         'categories': categories,
#         'category_id': int(category_id)
#     })

def detail(request, pk):
    
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[0:3]
    
    return render(request, 'item/detail.html', {
        'item': item,
        'related_items': related_items,
        })

@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)
        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            form.save()

            return redirect('item:detail', pk=item.id)
    else:
        form = NewItemForm()

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'New Item',
    })

@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)
        if form.is_valid():
            form.save()

            return redirect('item:detail', pk=item.id)
    else:
        form = EditItemForm(instance=item)

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Edit Item',
    })


@login_required
def delete(request,pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()
    return redirect('dashboard:index')

item/templates/item/browse.html
{% extends 'core/base.html' %}
{% block title %}Item{% endblock %}
{% block content %}
<div class="pb-6 grid grid-cols-4 gap-4 bg-yellow-400 rounded-xl">
    <div class="col-spin-1" style="text-align: center;">
        <form method="get" action="{% url 'item:browse' %}">
            <input name="query" class="w-22 py-2 px-2 border rounded-xl" type="text" value="{{query}}" placeholder="Find a bike, a chair or car...">

            <button class="mt-2 py-2 px-2 text bg-teal-500 text-white rounded-xl">Search</button>
        </form>

        <hr class="my-6">

        <p class="text-center font-semibold">Categories</p>

        <ul class="space-y-1 flex flex-col items-center">
            {% for category in categories %}
                <li class="w-40 py-2 px-2 rounded-xl{% if category.id == category.id %} bg-teal-200{% endif %}">
                    <a href="{% url 'item:browse' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
                </li>
            {% endfor %}
        </ul>
  
        <hr class="my-6">

        <p class="font-semibold">Clear Filter</p>
  
        <ul>
            <li><a href="{% url 'item:browse' %}" class="mt-2 py-4 px-8 inline-block bg-yellow-500 text-lg rounded-xl text-white">Clear</a> </li>
        </ul>
    </div>

    <div class="col-span-3">
        <div class="grid grid-cols-5 gap-5">

                {% for item in items %}
                    <div>
                        <a href="{% url 'item:detail' item.id %}">
                            <div>
                                <img src="{{ item.image.url }}" class="rounded-t-xl">
                            </div>

                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-2xl">{{ item.name }}</h2>
                                <p class="text-gray-500">Price: {{ item.price }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
    </div>
</div>
{% endblock %}

item/templates/item/detail.html
{% extends "core/base.html" %}

{% block title %} {{ item.name }} {% endblock %}

{% block content %}
<div class="grid grid-cols-5 gap-6 col-span-6 p-2 bg-yellow-400 rounded-xl">
        <img src="{{ item.image.url }}" class="w-35 h-auto rounded-xl">
        <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
        <p class="text-white"><strong>Price: </strong>{{ item.price }}</p>
        <p class="text-white"><strong>Seller: </strong>{{ item.created_by.username }}</p>
        {% if item.descroption %}
        {% if request.user == item.created_by %}
            <div class="mt-6 p-6 bg-yellow- rounded-xl">
                <p>This is your item! </p>
                <a href="{% url 'item:edit' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg front-semibold bg-green-500 text-white rounded-xl">Edit</a>
                <a href="{% url 'item:delete' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg front-semibold bg-red-500 text-white rounded-xl">Delete</a>
            </div>
        {% else %}
            <a href="{% url 'conversation:new' item.id %}" class="inline-block mt-9 px-8 py-6 text-lg front-semibold bg-teal-400 text-white rounded-xl hover:bg-teal-700">Contact Seller</a>
        {% endif %}
        <p class="text-white">
            <strong class="text-white">Description:</strong>
            {{ item.descroption }}
        </p>
        {% endif %}        
</div>
 <div class="mt-2 px-2 py-2 bg-yellow-400 rounded-lg">
            <h2 class="mb-2 text-xl text-white text-center">Related Items</h2>
            
            <div class="grid grid-cols-7 gap-7">

                {% for item in related_items %}
                    <div>
                        <a href="{% url 'item:detail' item.id %}">
                            <div>
                                <img src="{{ item.image.url }}" class="rounded-t-xl">
                            </div>

                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-2xl">{{ item.name }}</h2>
                                <p class="text-gray-500">Price: {{ item.price }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
    </div>
{% endblock %}

item/templates/item/form.html
{% extends "core/base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<div class="bg-yellow-400 p-8 rounded-xl shadow-md">
    <h1 class="mb-6 text-3xl">{{ title }}</h1>

    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}

        <div class="space-y-4">
            {{ form.as_p }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-400 rounded-xl ">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}    

        <button class="mt-6 py-2 px-6 text-lg bg-green-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}